# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



**Arewa Data Science Academy**

**Deep Learning Cohort 1.0**

**Name: Abdulrahman Abdullahi Garba**

**Email: abdulrahmanabdullahigarba@gmail.com**

**Title: Week 1 Solution**

In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch
# Create random tensor
random = torch.rand(size = (7, 7))
random

tensor([[0.1799, 0.6365, 0.9419, 0.1368, 0.7999, 0.8658, 0.6240],
        [0.6297, 0.1723, 0.3819, 0.8732, 0.9639, 0.0625, 0.2060],
        [0.5595, 0.6773, 0.5750, 0.8281, 0.4595, 0.1019, 0.7243],
        [0.2069, 0.6368, 0.8009, 0.6234, 0.3033, 0.4304, 0.0286],
        [0.7545, 0.6755, 0.8615, 0.1438, 0.2675, 0.7273, 0.9466],
        [0.7210, 0.4247, 0.2496, 0.0260, 0.6359, 0.7436, 0.6297],
        [0.5450, 0.3955, 0.1602, 0.3927, 0.2484, 0.2920, 0.8730]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
new_random = torch.rand(size = (1, 7))
torch.transpose(new_random, 0, 1)
# Perform matrix multiplication
random * new_random

tensor([[0.1514, 0.2009, 0.3982, 0.0096, 0.3660, 0.5294, 0.5566],
        [0.5301, 0.0544, 0.1614, 0.0613, 0.4411, 0.0382, 0.1838],
        [0.4710, 0.2138, 0.2431, 0.0581, 0.2103, 0.0623, 0.6460],
        [0.1742, 0.2010, 0.3386, 0.0437, 0.1388, 0.2632, 0.0255],
        [0.6352, 0.2132, 0.3642, 0.0101, 0.1224, 0.4447, 0.8443],
        [0.6070, 0.1341, 0.1055, 0.0018, 0.2910, 0.4547, 0.5616],
        [0.4588, 0.1249, 0.0677, 0.0275, 0.1137, 0.1785, 0.7786]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor1 = torch.rand(size = (7, 7))
random_tensor2 = torch.rand(size = (7, 1))
# Matrix multiply tensors
torch.matmul(random_tensor1, random_tensor2)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(123)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
random_on_gpu1 = torch.rand((2, 3), device = 'cuda')
random_on_gpu2 = torch.rand((2, 3), device = 'cuda')
print(random_on_gpu1)
print(random_on_gpu2)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
transpose_random_on_gpu2 = torch.transpose(random_on_gpu2, 0, 1)
result = torch.matmul(random_on_gpu1, transpose_random_on_gpu2)
result

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max_value = torch.max(result)
# Find min
min_value = torch.min(result)

In [ ]:
print("Maximum value: ", max_value)
print("Minimum value: ", min_value)

Maximum value:  tensor(0.7668, device='cuda:0')
Minimum value:  tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
max_index = torch.argmax(result)
print("Maximum Index Value: ", max_index)
# Find arg min
min_index = torch.argmin(result)
print("Minimum Index Value: ", min_index)

Maximum Index Value:  tensor(1, device='cuda:0')
Minimum Index Value:  tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand_tensor_4d = torch.rand((1, 1, 1, 10))

# Remove single dimensions
rand_tensor_1d = rand_tensor_4d.squeeze()
# Print out tensors and their shapes
print(f"The first tensor is {rand_tensor_4d}, and the shape is {rand_tensor_4d.shape}")
print(f"The second tensor is {rand_tensor_1d}, and the shape is {rand_tensor_1d.shape}")


The first tensor is tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), and the shape is torch.Size([1, 1, 1, 10])
The second tensor is tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), and the shape is torch.Size([10])
